apiVersion: v1
kind: Namespace
metadata:
  name: kardon-dev
  labels:
    app: kardon
    env: development

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kardon-config
  namespace: kardon-dev
data:
  # Infrastructure Services in kardon-prod
  POSTGRES_HOST: "prod-kardon-db.kardon-prod.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "kardon"
  POSTGRES_USER: "kardon"
  POSTGRES_PASSWORD: "kardon"

  REDIS_HOST: "prod-kardon-redis.kardon-prod.svc.cluster.local"
  REDIS_PORT: "6379"

  RABBITMQ_HOST: "prod-kardon-mq.kardon-prod.svc.cluster.local"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "kardon"
  RABBITMQ_PASSWORD: "kardon"
  RABBITMQ_VHOST: "kardon"

  AWS_S3_ENDPOINT_URL: "http://prod-kardon-minio.kardon-prod.svc.cluster.local:9000"
  AWS_S3_BUCKET_NAME: "uploads"
  AWS_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: "access-key"
  AWS_SECRET_ACCESS_KEY: "secret-key"

  # App Settings
  DEBUG: "true"
  ALLOWED_HOSTS: "*"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:8080,http://localhost:3001,http://localhost:3002,http://localhost:3100"

  # File Upload
  FILE_SIZE_LIMIT: "5242880"

  # Secrets
  SECRET_KEY: "klqy2k1uhkrjag1tsbz3kfk5sl17r0ptb2m07t4h075211zu0r"
  LIVE_SERVER_SECRET_KEY: "secret-key"

  # Other settings
  USE_MINIO: "1"
  MINIO_ENDPOINT_SSL: "0"
