apiVersion: v1
kind: Secret
metadata:
  name: kardon-secrets
  namespace: kardon-dev
type: Opaque
stringData:
  POSTGRES_USER: "kardon"
  POSTGRES_PASSWORD: "kardon"
  POSTGRES_DB: "kardon"
  PGDATA: "/var/lib/postgresql/data"

  REDIS_HOST: "kardon-redis"
  REDIS_PORT: "6379"

  RABBITMQ_HOST: "kardon-mq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "kardon"
  RABBITMQ_PASSWORD: "kardon"
  RABBITMQ_VHOST: "kardon"

  AWS_REGION: ""
  AWS_ACCESS_KEY_ID: "access-key"
  AWS_SECRET_ACCESS_KEY: "secret-key"
  AWS_S3_ENDPOINT_URL: "http://kardon-minio:9000"
  AWS_S3_BUCKET_NAME: "uploads"

  SECRET_KEY: "klqy2k1uhkrjag1tsbz3kfk5sl17r0ptb2m07t4h075211zu0r"

  LIVE_SERVER_SECRET_KEY: "secret-key"

  USE_MINIO: "1"
  MINIO_ENDPOINT_SSL: "0"

  CERT_EMAIL: ""
  CERT_ACME_CA: "https://acme-v02.api.letsencrypt.org/directory"
