apiVersion: apps/v1
kind: Deployment
metadata:
  name: beat-worker
  namespace: kardon
  labels:
    app: beat-worker
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beat-worker
  template:
    metadata:
      labels:
        app: beat-worker
        tier: backend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: beat-worker
          image: ghcr.io/h3xkatana/microhack-kardon/beat-worker:latest
          imagePullPolicy: Always
          command: ["./bin/docker-entrypoint-beat.sh"]
          envFrom:
            - configMapRef:
                name: kardon-config
            - secretRef:
                name: kardon-secrets
          env:
            - name: CELERY_BEAT
              value: "true"
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: beat-worker
  namespace: kardon
  labels:
    app: beat-worker
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: beat-worker
