apiVersion: batch/v1
kind: Job
metadata:
  name: migrator
  namespace: kardon
  labels:
    app: migrator
    tier: backend
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: migrator
        tier: backend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      restartPolicy: Never
      containers:
        - name: migrator
          image: ghcr.io/h3xkatana/microhack-kardon/migrator:latest
          imagePullPolicy: Always
          command: ["./bin/docker-entrypoint-migrator.sh"]
          envFrom:
            - configMapRef:
                name: kardon-config
            - secretRef:
                name: kardon-secrets
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
